services:
  kavita:
    image: lscr.io/linuxserver/kavita:latest
    container_name: kavita
    volumes:
      - /mnt/P_KNOWLEDGE/Comic/同人:/comic/maniax:ro
      - /mnt/P_KNOWLEDGE/Comic/商業:/comic/pro:ro
      - ./kavita_mnt:/config
    restart: unless-stopped
    networks:
      - public_network
      - monitoring_network

  stpageflip:
    image: nginx:alpine
    container_name: stpageflip
    volumes:
      - ./stpageflip:/usr/share/nginx/html:ro
      - /mnt/P_KNOWLEDGE/Comic/同人:/usr/share/nginx/html/comic/maniax:ro
      - /mnt/P_KNOWLEDGE/Comic/商業:/usr/share/nginx/html/comic/pro:ro
    restart: unless-stopped
    networks:
      - public_network
      - monitoring_network

networks:
  public_network:
    external: true

  monitoring_network:
    external: true
