services:
  komga-n:
    image: gotson/komga:latest
    container_name: komga-n
    restart: unless-stopped
    volumes:
      - ./komga-n_mnt/config:/config
      - /mnt/P_KNOWLEDGE/Comic/同人:/data/maniax:ro
      - /mnt/P_KNOWLEDGE/Comic/商業:/data/pro:ro
    environment:
      - TZ=Asia/Tokyo
    networks:
      - public_network

  komga-viewer-n:
    image: nginx:alpine
    container_name: komga-viewer-n
    restart: unless-stopped
    environment:
      - KOMGA_API_KEY=${KOMGA_API_KEY}
    volumes:
      - ./komga-viewer-n:/usr/share/nginx/html:ro
      - ./nginx-viewer-n.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - public_network
    depends_on:
      - komga-n

networks:
  public_network:
    external: true
