services:
  komga-n:
    image: gotson/komga:latest
    container_name: komga-n
    restart: unless-stopped
    volumes:
      - ./komga-n_mnt/config:/config
      - /mnt/P_KNOWLEDGE/Comic/同人:/data/maniax:ro
      - /mnt/P_KNOWLEDGE/Comic/商業:/data/pro:ro
    environment:
      - TZ=Asia/Tokyo
    networks:
      - public_network

networks:
  public_network:
    external: true
