services:
  komga-viewer:
    image: nginx:alpine
    container_name: komga-viewer
    volumes:
      # dist を配置したディレクトリを nginx にマウント
      - ./komga-viewer/dist:/usr/share/nginx/html:ro
      # nginx の設定ファイル
      - ./komga.viewer.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
    networks:
      - public_network

networks:
  public_network:
    external: true
